---
- name: ec2 instance
  hosts: localhost
  become: yes
  tasks:
  - name: launching ec2 instance
    ec2:
     instance_type: t2.micro
     key_name: mumbaikeypair
     image: ami-0f152f0680abc7ff2
     region: ap-south-1
     group: default
     count: 1
     wait: yes
     aws_access_key: AKIAVJIAN6LN5WASNFUP
     aws_secret_key: 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
     