---
- name: ec2 instance
  hosts: localhost
  become: yes
  tasks:
  - name: launching ec2 instance
    ec2:
     instance_type: t2.micro
     key_name: mumbaikeypair
     image: ami-0f152f0680abc7ff2
     region: ap-south-1
     group: Ansible
     count: 1
     wait: yes
     assign_public_ip: yes
     aws_access_key: AKIAIDB53UGRIVTLFXGA
     aws_secret_key: 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
     