---
- name: ec2 instance
  hosts: localhost
  become: yes
  tasks:
  - name: launching ec2 instance
    ec2:
     instance_type: t2.micro
     key_name: mumbaikeypair
     image: ami-0f152f0680abc7ff2
     region: ap-south-1a
     group: default
     vpc_subnet_id: subnet-0120a47a
     count: 1
     wait: yes
     aws_access_key: AKIAVJIAN6LN7QJURM47
     aws_secret_key: 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
     