---
- name: create tomcat group
  group:
    name: tomcat
    state: present

- name: i want to create a tomcat user
  user:
    name: tomcat
    shell: /bin/false
    home: /opt/tomcat 
    comment: my tom user
    groups: tomcat
    